export const FETCH_POSTS = "RECIPE/FETCH_POSTS";
export const FETCH_POSTS_LOADING = "RECIPE/FETCH_POSTS_LOADING";
export const FETCH_POSTS_SUCCESS = "RECIPE/FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILURE = "RECIPE/FETCH_POSTS_FAILURE";
